### ISSUE TITLE
Some Characters not Working Properly

### ISSUE THREAD

**Issue by NazaDwnt3d** [chrispo-git/ult-s#480]
Two characters, Wario and Sora, have major bugs/glitches that are unable to be resolved by simple means. 

-If Wario is excluded using the installer, he will not function properly, and becomes uncontrollable and stuck in place when side special is used
-If Sora counters a move from bomberman, the game will immediately crash

These issues are generally unavoidable when using these characters in gameplay and it kinda ruins the modpack, one bad apple spoils the bunch. (In this case two)

**Comment by NazaDwnt3d** [comment]
Well it got closed as "not planned". 
What's the point of having an installer if the characters that are excluded don't work properly? 🤦

**Comment by daniel-28m** [comment]
Yes, I also created a post about this problem with the Wario bug on the bike, but it is also closed :C

**Comment by EllaOW** [comment]
when these issues get closed, you can see from the category description why it might be. The issue was likely either unfixable or unreproduceable from our side. The problem with smash modding is that mixing different gameplay mods or trying to take stuff out post compilation can cause a lot of errors. Chrispo's decision to include the installer gave some workarounds for people who really wanted specific movesets, but at the end of the day the mod is designed to be played whole and as is, and including the installer as a solution to the people who refused to read our FAQ or rules about adding or taking out characters doesn't mean that additional hours will be spent by Chrispo to fix issues that would be fixed by simply playing the mod as it's meant to be played.
